### ISSUE TITLE
About the single cell mutiome data

### ISSUE THREAD

**Issue by dannihong** [GreenleafLab/Brain_ASD#1]
Dear author,
        Thanks for your great work. After reading your paper, I am interested the single cell mutiome data for PCW21, can you upload the data. Thanks a lot.

**Comment by lsundaram** [comment]
We are in the process of making this data public. We will get back to you shortly on this!! thank you

**Comment by cynthier** [comment]
Dear author,
Thanks for your awesome work also. After reading your paper, I want to know more about the scRNA_cluster_markers data and I found the related file (data_files/rds/scRNA_Cluster_Markers.RDS) shown in your code. Could you please upload the data. Thanks greatly.

**Comment by lsundaram** [comment]
There is another github associated with the project : https://github.com/GreenleafLab/brainchromatin. In there please take a look at the links.txt . We have multiome data information there. Please feel free to post another issue in that repo if there are any additional data that you would require. Thank you.
