### ISSUE TITLE
about the scRNA_clusters_markers

### ISSUE THREAD

**Issue by cynthier** [GreenleafLab/Brain_ASD#2]
Dear author,
Thanks for your awesome work also. After reading your paper, I want to know more about the scRNA_cluster_markers data and I found the related file (data_files/rds/scRNA_Cluster_Markers.RDS) shown in your code. Could you please upload the data. Thanks greatly.

**Comment by lsundaram** [comment]
Hi , there is another repo for the single cell analysis that is here : https://github.com/GreenleafLab/brainchromatin

In there please look at the get_data.sh to script and the links.txt to obtain all the files.
